### ISSUE TITLE
README: consolidate READMEs in to main README.md and use collapsed divs

### ISSUE THREAD

**Issue by luzpaz** [Malendryn/Enhanced-FreeCAD-3mf-Exporter#4]
Suggestion: for convenience for the end user consider employing [collapsible divs/sections](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab) to hide verbose sections (that are now split in to separate READMEs.

Also consider utilizing [markdown syntax](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to highlight and differentiate content.

**Comment by Malendryn** [comment]
This is a down-the-road consideration as I don't presently know markdown language!  :)  But it is something I would like to get around to!

**Comment by Malendryn** [comment]
All done!  README_HowToUse.md is no more, and README.md is now properly marked down!
