### ISSUE TITLE
Have you heard of the FreeCAD addon: FreeCAD Slic3r Tools ?

### ISSUE THREAD

**Issue by luzpaz** [Malendryn/Enhanced-FreeCAD-3mf-Exporter#7]
Just wondering? 

> This module lets you quickly export all visible parts in the current document, and open the resulting .stl file in Slic3r. You can also set up a default print profile, and directly get information about the resources that would be used to print it, as well as quickly generate the .gcode file.

https://github.com/limikael/freecad-slic3r-tools

Note: slic3r development looks stalled. The Addon also looks stalled or even abandoned.

**Comment by Malendryn** [comment]
Can't say I've heard of it!  But since it's talking about .stl files, it's kinda irrelevant :) (.stl files are incapable of carrying the data that the .3mf file is permitting me to do!)

But yeah, slic3r is pretty much dead and buried these days.  Last time I used it was years ago when I was still using Repetier Host as my slicer.   The Slic3r.org homepage shows the latest release date for Slic3r is version 1.3.0 dated 05/10/2018.

**Comment by luzpaz** [comment]
I was thinking you could look at the code to see how the addon remotely triggers Slic3r, which could be useful with your endeavors with Cura? Just spitballing.

**Comment by Malendryn** [comment]
Could be worth a look-see!  But at the same time I want to be careful not to tie the converter directly to any one software either.  I still have hopes of making this work in Prusaslicer among others, (I've looked inside a Prusa .3mf file and it's -massively- different in the way they save and load their per-model properties!  They don't even keep the values stored in the same single file, like Cura does! 

That's a headache for another day :)  Right now I'm working on making the exporter under stand grouped objects (in FreeCAD terms that would be a yellow 'Part' object.  ...Kinda have it working, but parts inside of parts are giving me hiccups. (mostly the translation matrix is out of kilter)

**Comment by luzpaz** [comment]
> But at the same time I want to be careful not to tie the converter directly to any one software either.  

That makes sense. Maybe in some later iteration you'd turn this in to a workbench and have support for multiple programs. Each on would have it's own preference tab. 

Or it may not be of interest to consolidate them in to one workbench, but each have their own workbench ? (just spitballing)

Edit: I'll close this ticket for now
